universe = vanilla

executable = condor-run-inference.sh

# Arguments:
label = ml2ml-paper-1
# injection_index, supplied by $(Process)
sampler = pocomc
pe_run_type = ml2ml
nlive = 1024
threshold = 0.2
npool = 4
pytorch_threads = 1

arguments = $(label) $(Process) $(sampler) $(pe_run_type) $(nlive) $(threshold) $(npool) $(pytorch_threads)

# Match this to nessai_npool * pytorch_threads.
# For arguments ending in "8 1", request_cpus = 8.
# For "8 2", use request_cpus = 16.
request_cpus = 8

# My memory usage usually remains below 1000MB, while disk usage is almost nil!
request_memory = 4 GB
request_disk = 4 GB

# Keep this CPU-only for now. Do not request GPUs for n_pool > 1.
# request_gpus = 0

initialdir = /home/suyog.garg/phd-main/umami

output = logs/inference_$(Cluster)_$(Process).out
error  = logs/inference_$(Cluster)_$(Process).err
log    = $(initialdir)/logs/inference_$(Cluster).log

# NOTE: output and error files are written by the worker process, which may have NFS storage cache sync issues and not see the `logs` dir, so we create those files in the root dir and then transfer them manually!

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = inference_$(Cluster)_$(Process).out, inference_$(Cluster)_$(Process).err

# Admin disabled getenv=True, so pass only what we need.
# Keep CUDA hidden for CPU multiprocessing safety.
# getenv = True
environment = "OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 VECLIB_MAXIMUM_THREADS=1 TORCH_NUM_THREADS=1 PYTHONUNBUFFERED=1"


+JobBatchName = "umami_ml2ml_pocomc_test"

# Remove or modify these if CIT requires a specific accounting group.
accounting_group = ligo.dev.o4.cbc.explore.test
accounting_group_user = suyog.garg

# Good safety behavior.
notification = Error

queue 256