# HTCondor Submit File

universe                = vanilla
executable              = condor-run-optimize.sh

if defined epochs
    arg_epochs = $(epochs)
else
    arg_epochs = 10

arguments = $(arg_epochs)

initialdir = /home/suyog.garg/phd-main/umami

output = logs/optimize_$(Cluster)_$(Process).out
error  = logs/optimize_$(Cluster)_$(Process).err
log    = $(initialdir)/logs/optimize_$(Cluster).log

# Resource Requests - Kept low for fast queue matching
request_gpus            = 2
request_cpus            = 1
request_memory          = 20G
request_disk            = 4G

# File Transfer Configurations
should_transfer_files   = NO

# FORCE HTCondor to find an A100-80GB node
Requirements = (Target.GPUs_DeviceName == "NVIDIA A100-SXM4-80GB") && (Target.HasGraphicsDriver == True)


# Remove or modify these if CIT requires a specific accounting group.
accounting_group = ligo.dev.o4.cbc.explore.test
accounting_group_user = suyog.garg

# Good safety behavior.
notification = Error

# Queue the job
queue 1
