# HTCondor Submit File
universe                = vanilla
executable              = condor-run.sh

# Output files for logs and tracking
output                  = job_$(Cluster)_$(Process).out
error                   = job_$(Cluster)_$(Process).err
log                     = job_$(Cluster)_$(Process).log

# Resource Requests - Kept low for fast queue matching
request_gpus            = 1
request_cpus            = 4
request_memory          = 16G
request_disk            = 100G

# File Transfer Configurations
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
# Include modelconfig-running.json if it is not already on the cluster's shared storage
transfer_input_files    = modelconfig-running.json

# Queue the job
queue 1
