universe = vanilla

executable = condor-run-inference.sh

# Arguments:
if defined label
    arg_label = $(label)
else
    arg_label = ml2ml-paper-1
endif
# injection_index, supplied by $(Process)
if defined injection_index_start
    arg_idx_start = $(injection_index_start)
else
    arg_idx_start = 0
endif
if defined sampler
    arg_sampler = $(sampler)
else
    arg_sampler = pocomc
endif
if defined pe_run_type
    arg_run_type = $(pe_run_type)
else
    arg_run_type = ml2ml
endif
if defined nlive
    arg_nlive = $(nlive)
else
    arg_nlive = 1024
endif
if defined threshold
    arg_threshold = $(threshold)
else
    arg_threshold = 0.2
endif
if defined npool
    arg_npool = $(npool)
else
    arg_npool = 4
endif
if defined pytorch_threads
    arg_pytorch_threads = $(pytorch_threads)
else
    arg_pytorch_threads = 1
endif
if defined total_jobs
    arg_total_jobs = $(total_jobs)
else
    arg_total_jobs = 256
endif

injection_index = $(Process) + $(arg_idx_start)

arguments = $(arg_label) $(injection_index) $(arg_sampler) $(arg_run_type) $(arg_nlive) $(threshold) $(arg_npool) $(arg_pytorch_threads)

# Match this to nessai_npool * pytorch_threads.
# For arguments ending in "8 1", request_cpus = 8.
# For "8 2", use request_cpus = 16.
request_cpus = 8

# My memory usage usually remains below 1000MB, while disk usage is almost nil!
request_memory = 8 GB
request_disk = 2 GB

# Keep this CPU-only for now. Do not request GPUs for n_pool > 1.
# request_gpus = 0

initialdir = /home/suyog.garg/phd-main/umami

output = logs/inference_$(Cluster)_$(Process).out
error  = logs/inference_$(Cluster)_$(Process).err
log    = $(initialdir)/logs/inference_$(Cluster).log

# NOTE: output and error files are written by the worker process, which may have NFS storage cache sync issues and not see the `logs` dir, so we create those files in the root dir and then transfer them manually!

should_transfer_files = NO

# Admin disabled getenv=True, so pass only what we need.
# Keep CUDA hidden for CPU multiprocessing safety.
# getenv = True
environment = "OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 VECLIB_MAXIMUM_THREADS=1 TORCH_NUM_THREADS=1 PYTHONUNBUFFERED=1"


+JobBatchName = "umami_ml2ml_pocomc_test"

# Remove or modify these if CIT requires a specific accounting group.
accounting_group = ligo.dev.o4.cbc.explore.test
accounting_group_user = suyog.garg

# Good safety behavior.
notification = Error

queue $(arg_total_jobs)